name: Github Release Management
on:
  push:
    branches:
      - master
jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Artifacts
        uses: actions/setup-node@v2
        env:
          NODE_ENV: production
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: Upload Artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*
